Repository datalayer/jupyter-kernel-client, pull requests merged in 2024-12, with the labels that each got.

#2 Add KernelClient.execute_interactive
  CHANGELOG.md
  jupyter_kernel_client/client.py
Labels: enhancement

#3 Multiple enhancement
  .github/workflows/build.yml
  .github/workflows/lint.sh
  .licenserc.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  conftest.py
  jupyter_kernel_client/client.py
  jupyter_kernel_client/consoleapp.py
  jupyter_kernel_client/constants.py
  jupyter_kernel_client/tests/conftest.py
  jupyter_kernel_client/tests/test_client.py
  pyproject.toml
Labels: enhancement

#5 Improve output_hook API
  jupyter_kernel_client/client.py
Labels: enhancement

#6 Add concurrency configuration on CI job
  .github/workflows/build.yml
Labels: enhancement

#7 Add pypi badge
  README.md
Labels: documentation

#8 Fix handling (not) owned kernel
  jupyter_kernel_client/client.py
Labels: bug

#10 Readme and Konsole
  README.md
  jupyter_kernel_client/konsoleapp.py
Labels: enhancement

#12 Add first implementation for list and get variables
  .github/workflows/fix-license-header.yml
  .licenserc.yaml
  Makefile
  README.md
  jupyter_kernel_client/__init__.py
  jupyter_kernel_client/__version__.py
  jupyter_kernel_client/client.py
  jupyter_kernel_client/konsoleapp.py
  jupyter_kernel_client/shell.py
  jupyter_kernel_client/snippets.py
  jupyter_kernel_client/tests/conftest.py
  jupyter_kernel_client/tests/test_client.py
  jupyter_kernel_client/utils.py
  jupyter_kernel_client/wsclient.py
  pyproject.toml
Labels: enhancement

#11 Capture exception on client stop
  jupyter_kernel_client/client.py
  jupyter_kernel_client/manager.py
Labels: enhancement

#14 Improve variables API
  jupyter_kernel_client/__init__.py
  jupyter_kernel_client/client.py
  jupyter_kernel_client/models.py
  jupyter_kernel_client/snippets.py
  jupyter_kernel_client/tests/test_client.py
  jupyter_kernel_client/wsclient.py
Labels: enhancement

#15 Fix version handling
  jupyter_kernel_client/__init__.py
  jupyter_kernel_client/_version.py
Labels: bug
